project:
  type: website

website:
  title: "Data Stories by Yao Lu"  
  navbar:
    background: dark               
    left:                           
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        href: posts/
      - text: "About"
        href: about.qmd
    right:                          
      - icon: github
        href: "https://github.com/yluu0123"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



